
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define LOG_LEVEL_APP LOG_LEVEL_NONE

#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_NONE

#define HEAPMEM_CONF_ARENA_SIZE 1024 * 30

#endif /* PROJECT_CONF_H_ */
